[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc_version = "0.8.20"
optimizer = true
optimizer_runs = 200
evm_version = "paris"

# For cleaner test output
ffi = true
verbosity = 3

# Remappings (if you use forge-std, OpenZeppelin, etc.)
remappings = [
    "forge-std/=lib/forge-std/src/",
   
]

# Testnet configuration
[rpc_endpoints]
sepolia = "https://eth-sepolia.infura.io/v3/https://arbitrum-sepolia.infura.io/v3/03fd3222776b4d13b0c7673167e44ed6"


